"""empty message

Revision ID: 1cedaf4fe50e
Revises: efda2eb78202
Create Date: 2016-01-14 23:40:12.284897

"""

# revision identifiers, used by Alembic.
revision = '1cedaf4fe50e'
down_revision = 'efda2eb78202'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
