"""empty message

Revision ID: 35f512126236
Revises: None
Create Date: 2016-01-13 21:35:53.457801

"""

# revision identifiers, used by Alembic.
revision = '35f512126236'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('profile_url', sa.String(length=2000), nullable=True),
    sa.Column('profile_serving_url', sa.String(length=2200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
