"""empty message

Revision ID: 55cffa52bd6e
Revises: d770dc3a4ad3
Create Date: 2016-01-15 23:47:52.224720

"""

# revision identifiers, used by Alembic.
revision = '55cffa52bd6e'
down_revision = 'd770dc3a4ad3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
