"""empty message

Revision ID: 73e66b622cd3
Revises: None
Create Date: 2016-01-10 14:43:33.458224

"""

# revision identifiers, used by Alembic.
revision = '73e66b622cd3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
