"""empty message

Revision ID: d770dc3a4ad3
Revises: 1cedaf4fe50e
Create Date: 2016-01-15 23:22:37.460197

"""

# revision identifiers, used by Alembic.
revision = 'd770dc3a4ad3'
down_revision = '1cedaf4fe50e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
